### ISSUE TITLE
Can't do anything in open-source code

### ISSUE THREAD

**Issue by AirmanRNC** [overbound/SonicTimeTwisted#182] opened 2021-07-28 01:16 UTC
When I open the game in GMS, none of my inputs work (I'm on keyboard by the way)

**Comment by AlexKhayrullin** [comment] 2021-07-28 06:19
Select a configuration in GMS before running the game:
![image](https://user-images.githubusercontent.com/2079839/127273290-84cf566d-5374-4b94-92ab-39d06eb8e2c2.png)

Configurations contain, among other things, default input methods and available input methods. For instance, Windows can use keyboards and gamepads, Android smartphones can use touchscreens and gamepads, Android consoles (NVidia Shield) only use gamepads, etc.

There is a task open for folding "Windows" back into "Default", but so far, nobody wants to do it :) 

I'll close the issue, since it's not a bug.

**Closed by AlexKhayrullin** 2021-07-28 06:19 UTC
