### ISSUE TITLE
Softlock on VVZ to DDZ transition

### ISSUE THREAD

**Issue by LucasMegaStriker** [overbound/SonicTimeTwisted#84] opened 2020-10-02 13:24 UTC
Happened sometimes when you beat Viridian Valley boss in the past or future and did the transition for start Drifting Dynamo Zone (sonic spins to a entrance, breaking obstacles and start DDZ) but instead of the level trigger starts, Sonic got stuck at the very left from DDZ wall and the controls get locked. 
When this happens, the level can be played after restart the game and select it on save game screen.
This also can happens before you even cross the DDZ entrance, If you walk slowly, the controls may dissapear if you don't reach the entrance in high speeds. Screenshots included.
![Screenshot_2020-10-02-10-20-55-591_com overboundstudio sttvm](https://user-images.githubusercontent.com/46081692/94927975-5f481900-0499-11eb-89e8-783341fd5bf3.png)
![Screenshot_2020-10-02-10-18-06-683_com overboundstudio sttvm](https://user-images.githubusercontent.com/46081692/94927993-63743680-0499-11eb-8397-98959a295421.png)

**Comment by nkrapivin** [comment] 2020-10-05 16:47
Were you playing the -YYC.apk build or the -VM.apk build?

**Comment by LucasMegaStriker** [comment] 2020-10-05 16:49
VM apk version.

**Comment by AlexKhayrullin** [comment] 2020-12-15 08:33
Should be fixed by now, but I won't know until I replay everything.

**Comment by AlexKhayrullin** [comment] 2021-01-04 16:52
The case where the controls don't appear should be fixed now, but I couldn't reproduce the part where Sonic gets stuck against the wall.

**Comment by AlexKhayrullin** [comment] 2021-01-04 21:00
OK, I understand it now. I thought there was a collision issue. It's just the controls not being there.
In this case, it's fixed now.

**Closed by AlexKhayrullin** 2021-01-04 21:00 UTC
Labels: android, bug
